"use client";

import { useState, useEffect, useTransition } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { ArrowLeft, Loader2, Sparkles, AlertCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { GuidedFlowSection } from "./guided-flow-section";
import type { GeneratedQuestion } from "@/lib/ai/generate-guided-questions";
import { EDITABLE_SECTIONS } from "@/types/sections";

type EditableSection = (typeof EDITABLE_SECTIONS)[number];

const SECTION_LABELS: Record<string, string> = {
  define: "Define",
  measure: "Measure",
  analyze: "Analyze",
  improve: "Improve",
  control: "Control",
};

type Answers = Record<string, string | null | undefined>;

type GuidedFlowWizardProps = {
  reportId: string;
  deviationNo: string;
};

function sectionCompletionCount(
  section: string,
  questions: GeneratedQuestion[],
  answers: Answers
): { answered: number; total: number } {
  const qs = questions.filter((q) => q.section === section);
  const answered = qs.filter(
    (q) => answers[q.id] !== undefined && answers[q.id] !== null
  ).length;
  return { answered, total: qs.length };
}

function isDefineSectionComplete(
  questions: GeneratedQuestion[],
  answers: Answers
): boolean {
  return questions
    .filter((q) => q.section === "define" && q.required)
    .every((q) => answers[q.id] !== undefined && answers[q.id] !== null && answers[q.id] !== "");
}

export function GuidedFlowWizard({ reportId, deviationNo }: GuidedFlowWizardProps) {
  const router = useRouter();
  const [activeSection, setActiveSection] = useState<EditableSection>("define");
  const [questions, setQuestions] = useState<GeneratedQuestion[]>([]);
  const [answers, setAnswers] = useState<Answers>({});
  const [loadingQuestions, setLoadingQuestions] = useState(true);
  const [questionsError, setQuestionsError] = useState<string | null>(null);
  const [generating, startGenerating] = useTransition();

  // Load questions on mount
  useEffect(() => {
    let cancelled = false;

    fetch(`/api/reports/${reportId}/guided-draft/questions`, { method: "POST" })
      .then(async (res) => {
        if (cancelled) return;
        if (!res.ok) {
          const body = (await res.json().catch(() => ({}))) as { error?: string };
          setQuestionsError(body.error ?? "Failed to load questions");
          return;
        }
        const data = (await res.json()) as { questions: GeneratedQuestion[] };
        setQuestions(data.questions);
      })
      .catch(() => {
        if (!cancelled) setQuestionsError("Failed to load questions. Please try again.");
      })
      .finally(() => {
        if (!cancelled) setLoadingQuestions(false);
      });

    return () => {
      cancelled = true;
    };
  }, [reportId]);

  const handleAnswer = (questionId: string, value: string) => {
    setAnswers((prev) => ({ ...prev, [questionId]: value }));
  };

  const handleDefer = (questionId: string) => {
    setAnswers((prev) => ({ ...prev, [questionId]: null }));
  };

  const canGenerate = !loadingQuestions && isDefineSectionComplete(questions, answers);

  const handleGenerate = () => {
    startGenerating(async () => {
      // Finalize answers: questions with no entry get deferred (null)
      const finalAnswers: Record<string, string | null> = {};
      for (const q of questions) {
        const val = answers[q.id];
        finalAnswers[q.id] = val === undefined ? null : (val ?? null);
      }

      const res = await fetch(`/api/reports/${reportId}/guided-draft`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ questions, answers: finalAnswers }),
      });

      if (!res.ok) {
        const body = (await res.json().catch(() => ({}))) as { error?: string };
        toast.error(body.error ?? "Failed to generate draft");
        return;
      }

      toast.success("Draft generated by Andrei — review and refine below");
      router.push(`/reports/${reportId}/edit`);
      router.refresh();
    });
  };

  return (
    <div className="flex min-h-screen flex-col">
      {/* Header */}
      <header className="sticky top-0 z-10 border-b border-[var(--border)] bg-[var(--background)]/95 backdrop-blur-sm">
        <div className="mx-auto flex max-w-5xl items-center gap-4 px-6 py-3">
          <Button
            variant="ghost"
            size="sm"
            className="gap-1.5 text-[var(--muted-foreground)]"
            onClick={() => router.push(`/reports/${reportId}/edit`)}
            disabled={generating}
          >
            <ArrowLeft className="size-4" />
            Back to report
          </Button>

          <div className="flex-1">
            <div className="flex items-baseline gap-2">
              <span className="text-sm font-semibold text-[var(--foreground)]">
                {deviationNo}
              </span>
              <span className="text-xs text-[var(--muted-foreground)]">
                Guided Flow
              </span>
            </div>
          </div>

          <Button
            onClick={handleGenerate}
            disabled={!canGenerate || generating || loadingQuestions}
            className="gap-2"
          >
            {generating ? (
              <Loader2 className="size-4 animate-spin" />
            ) : (
              <Sparkles className="size-4" />
            )}
            {generating ? "Generating draft…" : "Generate Draft"}
          </Button>
        </div>

        {/* Section tabs */}
        <div className="mx-auto max-w-5xl px-6">
          <div className="flex gap-0 border-t border-[var(--border)]">
            {EDITABLE_SECTIONS.map((section) => {
              const { answered, total } = sectionCompletionCount(section, questions, answers);
              const isActive = activeSection === section;
              return (
                <button
                  key={section}
                  type="button"
                  onClick={() => setActiveSection(section)}
                  className={`flex items-center gap-1.5 border-b-2 px-4 py-2.5 text-sm transition-colors ${
                    isActive
                      ? "border-[var(--brand-600)] text-[var(--brand-600)]"
                      : "border-transparent text-[var(--muted-foreground)] hover:text-[var(--foreground)]"
                  }`}
                >
                  {SECTION_LABELS[section]}
                  {!loadingQuestions && total > 0 && (
                    <span
                      className={`rounded-full px-1.5 py-0.5 text-[10px] font-medium ${
                        answered === total
                          ? "bg-emerald-100 text-emerald-700"
                          : answered > 0
                            ? "bg-amber-100 text-amber-700"
                            : "bg-[var(--muted)] text-[var(--muted-foreground)]"
                      }`}
                    >
                      {answered}/{total}
                    </span>
                  )}
                </button>
              );
            })}
          </div>
        </div>
      </header>

      {/* Main content */}
      <main className="mx-auto w-full max-w-5xl flex-1 px-6 py-8">
        {loadingQuestions ? (
          <div className="flex flex-col items-center justify-center gap-4 py-24">
            <Loader2 className="size-8 animate-spin text-[var(--brand-600)]" />
            <div className="text-center">
              <p className="font-medium text-[var(--foreground)]">
                Andrei is preparing your questions…
              </p>
              <p className="mt-1 text-sm text-[var(--muted-foreground)]">
                Analysing existing content and criteria
              </p>
            </div>
          </div>
        ) : questionsError ? (
          <div className="flex flex-col items-center justify-center gap-4 py-24">
            <AlertCircle className="size-8 text-destructive" />
            <div className="text-center">
              <p className="font-medium text-[var(--foreground)]">{questionsError}</p>
              <Button
                variant="outline"
                className="mt-4"
                onClick={() => {
                  setQuestionsError(null);
                  setLoadingQuestions(true);
                  fetch(`/api/reports/${reportId}/guided-draft/questions`, {
                    method: "POST",
                  })
                    .then(async (res) => {
                      if (!res.ok) throw new Error("Failed");
                      const data = (await res.json()) as {
                        questions: GeneratedQuestion[];
                      };
                      setQuestions(data.questions);
                    })
                    .catch(() => setQuestionsError("Failed to load questions. Please try again."))
                    .finally(() => setLoadingQuestions(false));
                }}
              >
                Try again
              </Button>
            </div>
          </div>
        ) : (
          <>
            {!isDefineSectionComplete(questions, answers) && activeSection !== "define" && (
              <div className="mb-6 flex items-center gap-2 rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">
                <AlertCircle className="size-4 shrink-0" />
                Complete the required Define questions before generating the draft.
              </div>
            )}

            {generating && (
              <div className="fixed inset-0 z-50 flex flex-col items-center justify-center gap-4 bg-[var(--background)]/80 backdrop-blur-sm">
                <Loader2 className="size-10 animate-spin text-[var(--brand-600)]" />
                <div className="text-center">
                  <p className="text-lg font-semibold text-[var(--foreground)]">
                    Andrei is writing your report…
                  </p>
                  <p className="mt-1 text-sm text-[var(--muted-foreground)]">
                    Generating all five DMAIC sections — this takes about 30–60 seconds
                  </p>
                </div>
              </div>
            )}

            <GuidedFlowSection
              section={activeSection}
              sectionLabel={SECTION_LABELS[activeSection] ?? activeSection}
              questions={questions}
              answers={answers}
              onAnswer={handleAnswer}
              onDefer={handleDefer}
              disabled={generating}
            />

            {/* Bottom navigation */}
            <div className="mt-8 flex items-center justify-between border-t border-[var(--border)] pt-6">
              <Button
                variant="outline"
                onClick={() => {
                  const idx = EDITABLE_SECTIONS.indexOf(activeSection);
                  if (idx > 0) setActiveSection(EDITABLE_SECTIONS[idx - 1]!);
                }}
                disabled={EDITABLE_SECTIONS.indexOf(activeSection) === 0 || generating}
              >
                <ArrowLeft className="mr-1.5 size-4" />
                Previous
              </Button>

              {EDITABLE_SECTIONS.indexOf(activeSection) <
              EDITABLE_SECTIONS.length - 1 ? (
                <Button
                  variant="outline"
                  onClick={() => {
                    const idx = EDITABLE_SECTIONS.indexOf(activeSection);
                    setActiveSection(EDITABLE_SECTIONS[idx + 1]!);
                  }}
                  disabled={generating}
                >
                  Next
                  <ArrowLeft className="ml-1.5 size-4 rotate-180" />
                </Button>
              ) : (
                <Button
                  onClick={handleGenerate}
                  disabled={!canGenerate || generating}
                  className="gap-2"
                >
                  {generating ? (
                    <Loader2 className="size-4 animate-spin" />
                  ) : (
                    <Sparkles className="size-4" />
                  )}
                  {generating ? "Generating draft…" : "Generate Draft"}
                </Button>
              )}
            </div>
          </>
        )}
      </main>
    </div>
  );
}
