export const CVP_DRAFTING_GUIDANCE = `CLEANING VALIDATION PROTOCOL (3xper QAD-SOP-PS-003-F08-00) — DRAFTING RULES

One protocol covers the cleaning validation of the manufacturing equipment train for one product / stage at one plant (e.g. Production Block-2). Write in formal GMP protocol language, 3xper Innoventure Limited, Naidupeta as the site. Future tense / “shall”. This document is the **protocol** (how the train will be cleaned and sampled across three consecutive batches). It is **not** the cleaning validation **report**. Execution cells stay blank; those values are recorded when the report is finalised. Never write chromatograms, pass/fail verdicts, observed residues, or executed batch IDs — even if a cleaning record is attached this turn. The three Batch columns stay blank in the protocol.

PROTOCOL vs REPORT — fill the plan; leave execution blank (from the ISM Stage-4 protocol form):
- **Fill:** cover identity (Protocol No., product, code, stage, plant, department, version, title — copy from the cover / CPDR; do not invent a protocol number); Objective / Scope / Responsibilities owners / Background / Pre-requisites; Qualification status, surface area, WAF, rinse volume, MACO, swab/rinse limits; Methodology, sampling procedure, section 14 location rules; 15.N identity, locations, rationale, and Limit/LOQ/LOD; nitrosamine/PGI seeded intro plus **Limit NMT** and one Name/ID row per equipment; process-line seeded intro/criteria plus **descriptions**; manufacturing-area seeded intro/criteria plus **Equipment ID** and **Verified by** (Production, then QA); overall **Equipment ID** rows and the acceptance-criteria table (write NA only where a test does not apply to that item, e.g. PFR visual/swab); testing-procedure / method-validation seeded intros plus spec / method / LOQ / LOD / recovery and method-validation status; Evaluation / Deviations / Revalidation shall-language (keep the seeded ISM Stage-4 paragraphs); related-document numbers (BCR “To be assigned” when unknown); History Version 00 / New document.
- **Leave blank:** 1.0 Name, Designation, Sign & date; cover and 24.0 History Effective date on Version 00 unless a cited page prints a date; 15.N.1 Date of Cleaning (do not invent that row; if present, Details stay empty); 15.N.2 BCR date when the BCR is still …-XXX-00; 15.N.4 every Batch 1 / Batch 2 / Batch 3 observed-value cell; 15.N.6 visual Batch 1 / Batch 2 / Batch 3 (all four rows); 15.N.7 / 15.N.8 Limit / LOQ / LOD criteria are written in Batch 1, Batch 2, and Batch 3 (the same text in each); Sample ID on those rows stays blank — do not merge cells; 15.N Inference / Conclusion beyond the seeded “It shall be written in the cleaning validation report.”; nitrosamine/PGI LOD, LOQ, and every per-equipment impurity **result** cell; process-line Production and QA observations; manufacturing-area Floor / Wall / Ceiling / AHU / External / Wipe / Overall Result / Sign & date; overall-results Visual / Swab / Rinse / Extraneous / Nitrosamine / PGI / Mfg area / Overall Status / Remarks **values** (NA is allowed; never Pass / Complies). The 15.0 batch execution summary Product batch No. / Cleaning date / BCR No. / Cleaned by / Verified by cells stay empty.

Cover identity (draft_identity, no citations): Protocol No. (CVRP-…), Name of the product, Product Code, Stage, Plant, Department (usually Production), Version, Effective Date, Document Title. Copy those from the protocol cover or change-control / CPDR header. Do not invent a protocol number. Leave Effective Date empty on Version 00 when no cited page prints a date.

Do not generate:
- Word drawings, grouped shapes, arrows, or text-box stacked fractions (MACO PDE×MBS/TDD brackets in the source form). Write the same arithmetic as table rows Attribute | Description | Value / Calculation, or as Unicode (n = √H + 1, SA × RF).
- Equipment-train diagrams, PFR flow schematics, swab-stroke figures, or labelled vessel sketches (S-1 on the top dish). Describe locations in tables (Location ID | Description). Use insert_image only when a cited attachment page is a figure the engineer asked to place.
- Two-row merged headers (Nitrosamine spanning NDMA…NDBA; PGI spanning three impurities; qualification dates on a continuation row under the protocol number). Use the seeded flat columns. One editor row per equipment (or Production then QA for manufacturing-area).
- Highlighted yellow “filled” cells, handwritten signatures, or chromatograms.

Do generate:
- Objective / Scope / Pre-requisites / Methodology / Sampling procedure / Swab locations / Evaluation / Deviations / Revalidation as prose from cited CPDR, PDR, BCR, qualification reports, and site SOPs.
- Tables with the seeded headers. Keep column order. Empty unused shells stay one blank row.
- Scope, Background (cleaning method / solvent), Qualification status, Surface area, Rinse-volume calculation, MACO equipment list, per-equipment rinse limits, Equipment sampling blocks, Process lines, Manufacturing area, Overall results (IDs + NA + acceptance criteria; execution cells blank), Testing procedure, Method validation status, Related documents, Annexures.

Standard pieces:
- Responsibilities: keep the seeded department rows; do not invent new functions. Fill only if a cited SOP names a different owner.
- WAF table (9.0): keep the four surface-type rows (polished SS, rough SS, glass lined, PTFE/Halar) unless a cited page prints different factors.
- Rinse Volume (L) = Surface Area (m²) × Rinse Factor (L/m²). Copy SA, RF, SAF, SF, considered volume, and sample quantity from a cited page when a cited page prints them. Call calculate with those numbers (no units) and write the display product into the rinse-volume RF / SAF cells (or \`SA × RF = product\`). Do not leave the unevaluated expression as the answer. The SAF formula is SA × SAF × SF. Considered volume is the rounded litre of that product unless the result is too small to flood or sample — then write a GMP operational floor (minimum to flood a 10" filter housing or vessel) without a citation. Do not cite a methodology page, WAF ranges in L/m², or an equipment capacity (PFR-1301 5 L HAS) as the source of a considered rinse volume or rinse sample quantity. Write those as Unicode prose or table rows — never wrap them in \`$$...$$\` or \`\\text{...}\`. Keep \`$$...$$\` only for a stacked fraction (\`\\frac\`).
- Health-based MACO = PDE × MBS / TDD; general-limit MACO = MBS × MAXCONC; use the lower value. PDE and TDD come from cited annexures, not from the product name.
- MACO (10.0) is three tables in one narrative. tableIndex 0 = equipment list (S. No. | Name of the Equipment | Equipment No. | Capacity | MOC | Is used for Stage-4? | Equipment used previous / subsequent to this product | Minimum batch size for this equipment manufactured | Product contact / Non-product contact). Copy those header words exactly. tableIndex 1 = health-based formula (Attribute | Description of Attribute | Value / Calculation — PDE, MBS, TDD, MACO). tableIndex 2 = general-limit formula (same three columns — MAXCONC, MBS, MACO). Copy tableIndex from read_section. Never draft_field this field. Never insert_rows of the formula headers into table 0.
- Swab locations (section 14.0): H > 2 m → n = √H + 1 (round up); H ≤ 2 m → one middle level. Diameter ≤ 1 m → 0° and 180°; > 1 m → 0°, 90°, 180°, 270°. Mandatory reactor locations: top dish, bottom dish, manhole, agitator, discharge valve (add thermowell when the cited FMEA / protocol lists it). Plug-flow / no-swab items skip this.
- Equipment sampling (15.1, 15.2, …) is a **protocol**, not a report. One TipTap box per Scope product-contact item (\`items.0\` = 15.1, \`items.1\` = 15.2). After 15.1 is filled, write 15.2 to \`items.1\` (or pass \`15.2\`) — the Add-equipment box if it exists; if it does not, the tool adds that box. Never create_table / insert_rows into a filled \`items.0\` for a new equipment. The empty box already has the **shared** 15.N boilerplate (intro with [Plant] / FMEA / [duty] slots, 15.N.1 details prose + identity table, 15.N.2 documents table, 15.N.5 heading, 15.N.7 residue intro + table, 15.N.8 extraneous prose + table, Inference/Conclusion). Keep those seeded sentences — fill the [slots] with propose_edit; do not rewrite them. Add equipment inserts that same blank 15.N template; never copy the previous item's filled tables. Do not dump 15.1–15.10 into one field. Rename the H2 with propose_edit (\`15.1 MIXED VESSEL (MV-1304)\` — NAME (ID) as on Scope).
  Empty leftover 15.N: **Do not draft_field** \`items.N\` (more than one seeded table). Use edit_table (identity tableIndex 0, documents 1, residue 2, extraneous 3) and propose_edit for slots / extra headings. **Redraft / replace / make 15.N as** a different equipment ID (or "insert it" after that rewrite is already in chat): call **draft_field** on \`items.N\` / \`15.N\` with replaceFilledField: true and the complete markdown for that box — do not dump the specification in chat, and do not rebuild it with piecemeal edit_table. After the identity / documents / residue tables have landed, leftover heading / 15.N.1 / 15.N.3 / 15.N.5 prose is **propose_edit** ("go for 15.N.1", "make these", "insert suggestions for 15.N.1") — zero open cards means create them; quote the heading and the paragraph after it only (one subsection per call); do not paste Table N / a GFM table or the remaining subsection in chat (the server strips those tables and still lands the paragraph). **Add a table** under an existing 15.N.x heading already in the saved box (e.g. add a table to 15.2.3.2): call **edit_table create_table** with afterAnchor quoting that heading — do not propose_edit the paragraph, and do not dump a GFM table. That is not leftover-prose recovery. create_table: omit title (no Table N. caption inside 15.N). After propose_edit of a new 15.N.3 / .6 heading, create_table with empty afterAnchor so the table pairs with that heading — do not afterAnchor a heading that is still an open card. Quote afterAnchor only for a heading already in the saved box (seeded 15.N.1 / .2 / .5 / .7). Finish this 15.N box in one burst (seed slots plus extra 15.N.3 / .6). Reuse a finished equipment-sampling document review for the next box — pass attachment ids (not filenames). Nitrosamine and PGI follow the last equipment block — do not number them 15.11 / 15.12. Do not hardcode MV-1304.
  Subsections are **not identical for every item**. 15.N.3 / 15.N.4 / 15.N.6 are **not** in the seed — add them from the type recipe with propose_edit heading + create_table. Headers for tables you create:
  Location ID | Description of location
  Parameter | Calculation | Value | Remarks
  Swab ID | Description | Rationale | No. of samples
  Cleaning Parameter | Acceptance Criteria / Target | Batch 1 | Batch 2 | Batch 3
  Sample description / location | Batch 1 | Batch 2 | Batch 3
  Sample description / location | Sample ID | Batch 1 | Batch 2 | Batch 3
  Equipment-type recipes:
  - **Vessel / reactor** (MV, GLR, SSR): add 15.N.3 (worst-case, shell-calc, pictorial, rationale) and 15.N.6 visual. Identity insert_rows: Shell height, Shell diameter, Type of agitator; add No. of baffles only when cited (MV/SSR). GLR typically has no baffles row. After 15.N.1 details prose, add: “These parameters shall be used to establish the shell wall swab sampling locations.”
  - **ML tank / receiver** (MLT): skip 15.N.3.2 (no shell height/diameter). Identity is one group: Capacity / MOC / Surface Area; Shell height, Shell diameter, Type of agitator, No. of baffles stay NA. Four worst-case swab IDs (top dish / inlet nozzle, inner wall, bottom cone / dish, bottom drain / transfer valve) — not reactor shell rows. Add 15.N.3.1, 15.N.3.4 rationale, 15.N.6 visual. Do not copy a vessel's S-1–S-n dish/agitator set onto an MLT box.
  - **Filter with ML tank** (ANF, ANFD): same extra blocks as a vessel. Identity is two stacked groups in the seeded Parameter | Details | Reference table, with a banner row for the filter then the ML tank (Capacity / MOC / Surface Area / Shell height / Shell diameter each). Copy the ML tank ID from **this** filter's cited drawing — not another item's tank. No agitator/baffles rows. Worst-case IDs are agitator, filter mesh, discharge port, ML tank inner surface — not reactor dishes.
  - **Specialty filter** (leaf filter, micron filter): same extra blocks as a vessel except skip 15.N.3.2 when identity has no shell height/diameter (micron filter: two cited swab locations only). Identity is one group without agitator/baffles; worst-case IDs are equipment-specific (dome, leaf, weld, header, cone, nozzle, valve — or the two cited IDs on a micron filter).
  - **No-swab item** (PFR / plug flow): do **not** add 15.N.3, 15.N.4, or 15.N.6. From 15.N.1 details prose drop “shell height, and shell diameter”. Identity insert_rows Shell length (not height); Shell diameter may stay blank when the cited drawing does. Retitle 15.N.7 to \`Rinse samples analysis results summary ([analyte] content)\` — no Swab banner.
  15.N.4 Cleaning operation is **not** on every item (the filled ISM Stage-4 protocol prints it only on the first vessel). Create that table only when a cited protocol prints it for that item. Use headers Cleaning Parameter | Acceptance Criteria / Target | Batch 1 | Batch 2 | Batch 3. The three Batch columns stay blank in the protocol. Do not invent observed quantities.
  Copy IDs and labels from the cited drawing / FMEA / qualification report for **this** item. Do not replay these ISM4 source mismatches: ANFD-1301's ML tank labelled MLT-1307 (that is ANF-1301's tank); LF-1302 qualification row labelled OQ while citing a PQ report; SSR-1305 rationale prose "S-8 to S-10" when the table IDs differ.
  Fill vs leave blank, and type-specific stock (copy these sentences when you add the subsection):
  - **Intro / 15.N.1 / 15.N.2 / 15.N.7 / 15.N.8** are already in the seed. Fill [Plant], FMEA/[Equipment ID], [product/stage], [duty], [analyte], [limit] from cited pages. Documents: label the last row OQ or PQ to match the cited report number (a PQR/… number is PQ, not OQ). **BCR date stays blank** when the BCR is still a placeholder (PB2-BCR-…-XXX-00). Qualification date may also be blank if the cited row is empty. Identity H/D stay in mm as printed; agitator/baffles cite the IQ report. Do not invent a blank parameter row.
  - **15.N.3.1 Worst-case locations** (swabbed items). “The following worst-case product-contact locations shall be included as mandatory swab sampling locations based on equipment design, accessibility, cleanability, and residue accumulation potential.” Table Location ID | Description of location. One row per S-n. Copy IDs from the cited FMEA / protocol — do not reuse MV dishes on a filter.
  - **15.N.3.2 Shell-wall calculation** (only when identity cites shell height and diameter — skip PFR and items with no shell, e.g. a micron filter). “The number of shell wall swab sampling locations shall be determined from the vessel shell height and diameter, to ensure representative coverage of the internal product-contact surface. Refer to Section 14.0.” Table Parameter | Calculation | Value | Remarks. Convert identity mm → m in Value (3908 mm → 3.9 m). Calculation is NA for H and D. n: H ≤ 2 m → Value \`1 #s\` and remarks “Height is <2 m, hence one horizontal level”; H > 2 m → Calculation \`√H+1\`, Value \`N #s\`, remarks name the level heights. C: D ≤ 1 m → two locations (0°, 180°); D > 1 m → four. Keep the Case 1 / Case 2 note in the C Parameter cell. Total = n × C as \`4 x 3\` / \`N #s\`. Call calculate for √H+1. Do not write a C of 4 when Case 1 applies.
  - **15.N.3.3 Pictorial.** “The following are the pictorial representation of the swab sampling locations as per identified worst-case product-contact locations.” Then insert_image only for a cited figure. Never invent a vessel sketch. If there is no figure, listing the S-IDs is enough.
  - **15.N.3.4 Rationale.** “Swab sampling locations have been selected on a risk basis from the equipment design and operation, considering accessibility, cleanability, residue accumulation potential and the extent of product-contact surface. They comprise the mandatory worst-case locations (S-1 to S-n) and representative locations on the vessel shell wall (S-…), the number of which is derived in Section 14.0.” Prose S-IDs must match this item's location/rationale tables — do not write a range the table does not contain. Table Swab ID | Description | Rationale | No. of samples. Every worst-case ID plus one grouped shell row per level (S-7a–d in one row, No. of samples = C). Vessel rationale is short stacked clauses (Product contact surface / Hard to clean / …). Filter / specialty locations are one or two sentences. No. of samples is 1 per worst-case ID and C for each shell-level group. Items with no shell have worst-case rows only (no grouped shell row).
  - **15.N.4 Cleaning operation** (only if a cited protocol prints it for that item). Shall-language that parameters shall be recorded at execution. Table Cleaning Parameter | Acceptance Criteria / Target | Batch 1 | Batch 2 | Batch 3. Parameter names and a few targets (“As per approved cleaning SOP”, “Minimal”) may be filled; **every Batch 1 / Batch 2 / Batch 3 observed-value cell stays empty.** Do not write Inference/Conclusion here.
  - **15.N.5** heading is seeded; write the type paragraph under it (prose only). Vessel / filter: “Upon completion of cleaning, the equipment shall undergo visual inspection under qualified inspection conditions. Following satisfactory visual inspection, swab samples shall be collected from predefined worst-case locations and final rinse samples shall be collected from the equipment. The results shall be evaluated against the established acceptance criteria to demonstrate the effectiveness and consistency of the cleaning procedure.” Reactors that collect reflux add a first sentence that reflux samples shall be collected during the reflux cleaning step and analysed for information. PFR: “Upon completion of cleaning, rinse sample shall be collected from the equipment. The results of rinse samples shall be evaluated against the established acceptance criteria to demonstrate the effectiveness and consistency of the cleaning procedure.”
  - **15.N.6 Visual inspection** (swabbed items only). “As a primary verification of equipment cleanliness, visual inspection shall be conducted under established inspection conditions to assess the presence of visible product residues, foreign matter, staining, or other indications of inadequate cleaning. The observations made by the Production Chemist, Production Shift In-charge, and QA representative during each of the three cleaning validation batches shall be recorded in the following table. Any permanent stains observed shall be evaluated to confirm that they do not impact the effectiveness of the cleaning process or product quality.” Table Sample description / location | Batch 1 | Batch 2 | Batch 3. Four rows, **Batch columns blank**: Production Chemist verification; Production Shift in-charge verification; QA verification; Is any permanent stain recorded?
  - **15.N.7 Residue.** Keep the seeded intro; fill [analyte] and [limit]. Retitle to name the **analyte actually held in that equipment** and the sample types: \`Reflux, Swab & Rinse…\` when reflux rows exist, \`Swab & Rinse…\` when both exist without reflux, \`Rinse samples…\` when rinse-only. insert_rows for locations above the Limit/LOQ/LOD footer; fill location + Sample ID; **Batch 1 / Batch 2 / Batch 3 stay empty.** Typical order: informational reflux/rinse-after-reflux rows (Sample ID NA, “for information”) when cited; Final Rinse Sample (Acetone) | NA; banner row “Swab samples” (label in the first cell only — leave the other cells blank, do not merge); one row per rationale ID (ungroup the shell a/b/c/d). Fill Limit / LOQ / LOD from the cited method-validation page (NMT … ppm) with the **same text in Batch 1, Batch 2, and Batch 3**. Sample ID on those rows stays blank. Do not invent ppm values. Do not set a colspan and do not add a merged Results / batch-number header.
  - **15.N.8 Extraneous.** Keep the seeded prose and Rinse Sample / Limit rows. The Limit sentence is the same text in Batch 1, Batch 2, and Batch 3; Sample ID on that row stays blank. Do not merge cells.
  - Keep the seeded **Inference:** / **Conclusion:** lines (“It shall be written in the cleaning validation report.”). Never draft a pass/fail inference in the protocol.
- Nitrosamine / PGI: keep the seeded intro; fill [limit] from a cited page with propose_edit (do not invent ppm). First data row is Limit NMT (ppm) across the impurity columns, then three Name/ID/Batch rows per equipment (Batch 1, Batch 2, Batch 3). Flattened columns are the form’s inner impurity names. **LOD, LOQ, and per-equipment result cells stay empty** (see PROTOCOL vs REPORT).
- Process lines: keep the seeded intro and Acceptance Criteria paragraphs. Fill descriptions; add a Batch column (Batch 1 / 2 / 3, three rows per line). **leave Production/QA observations empty**.
- Manufacturing area: keep the seeded intro, wipe-cloth paragraph, and Acceptance Criteria. Production then QA rows for each of Batch 1 / 2 / 3 with the same Equipment ID. The paper form merges that ID vertically — the editor does not. **Observation, Overall Result, and Sign & date stay empty**.
- Testing procedure (16.0) / method validation (17.0): keep the seeded intro; fill spec / method / LOQ / LOD / recovery and method-validation status from cited pages.
- Evaluation (18.0): keep the seeded four paragraphs (validated when all results comply; LOQ/LOD reporting; OOS re-clean with QA approval; cleaning validation report). Do not replace them with a three-batch recap — that rule lives in the overall-results criteria table.
- Overall results: three rows per equipment ID (Batch 1 / 2 / 3); NA where a test does not apply; **execution values stay empty**. Fill the acceptance-criteria table from this protocol’s limits, including “Number of batches | Three consecutive batches complying”. Prefatory sentence may be “Result fields are intentionally left blank for recording during report finalization.”
- 15.0 batch execution summary: three rows Batch 1 / Batch 2 / Batch 3; **Product batch No. / Cleaning date / BCR No. / Cleaned by / Verified by stay empty**.
- History: keep Version 00 / New document unless a cited revision exists. Effective date stays blank on v00 unless a cited page prints a date.
- Abbreviations: keep the seeded generic list; add product-specific nitrosamine or impurity abbreviations only when those names appear on a cited page.

Never invent equipment numbers, surface areas, protocol/report numbers, PDE, batch sizes, LOQ/LOD, or swab recoveries — copy them from a cited attachment page or leave the cell empty.

Litre capacities: write round thousands as k L (10000 L → 10k L, 8000 L → 8k L). Keep small volumes (150 L, 37 L), millilitres, kilograms, and printed kilolitres (10 KL, 3.0 KL).`;
