export const CVP_DRAFTING_GUIDANCE = `CLEANING VERIFICATION PROTOCOL (3xper QAD-SOP-PS-003-F08-00) — DRAFTING RULES

One protocol covers the cleaning verification of the manufacturing equipment train for one product / stage at one plant (e.g. Production Block-2). Write in formal GMP protocol language, 3xper Innoventure Limited, Naidupeta as the site. Future tense / “shall” for the protocol; do not write executed results unless a cited cleaning record or chromatogram is on this turn.

Cover identity (draft_identity, no citations): Protocol No. (CVRP-…), Name of the product, Product Code, Stage, Plant, Department (usually Production), Version, Effective Date, Document Title. Copy those from the protocol cover or change-control / CPDR header. Do not invent a protocol number.

Do not generate:
- Word drawings, grouped shapes, arrows, or text-box stacked fractions (MACO PDE×MBS/TDD brackets in the source form). Write the same arithmetic as table rows Attribute | Description | Value / Calculation, or as Unicode (n = √H + 1, SA × RF).
- Equipment-train diagrams, PFR flow schematics, swab-stroke figures, or labelled vessel sketches (S-1 on the top dish). Describe locations in tables (Location ID | Description). Use insert_image only when a cited attachment page is a figure the engineer asked to place.
- Two-row merged headers (Nitrosamine spanning NDMA…NDBA; PGI spanning three impurities; qualification dates on a continuation row under the protocol number). Use the seeded flat columns. One editor row per equipment (or Production then QA for manufacturing-area).
- Highlighted yellow “filled” cells, handwritten signatures, or chromatograms.

Do generate:
- Objective / Scope / Pre-requisites / Methodology / Sampling procedure / Swab locations / Evaluation / Deviations / Revalidation as prose from cited CPDR, PDR, BCR, qualification reports, and site SOPs.
- Tables with the seeded headers. Keep column order. Empty unused shells stay one blank row.
- Scope, Background (cleaning method / solvent), Qualification status, Surface area, Rinse-volume calculation, MACO equipment list, per-equipment rinse limits, Equipment sampling blocks, Process lines, Manufacturing area, Overall results, Testing procedure, Method validation status, Related documents, Annexures.

Standard pieces:
- Responsibilities: keep the seeded department rows; do not invent new functions. Fill only if a cited SOP names a different owner.
- WAF table (9.0): keep the four surface-type rows (polished SS, rough SS, glass lined, PTFE/Halar) unless a cited page prints different factors.
- Rinse Volume (L) = Surface Area (m²) × Rinse Factor (L/m²). Copy SA, RF, SAF, SF, considered volume, and sample quantity from a cited page. Call calculate with those numbers (no units) and write the display product into the rinse-volume RF / SAF cells (or \`SA × RF = product\`). Considered volume is the rounded litre. Do not leave the unevaluated expression as the answer. The SAF formula is SA × SAF × SF. Write those as Unicode prose or table rows — never wrap them in \`$$...$$\` or \`\\text{...}\`. Keep \`$$...$$\` only for a stacked fraction (\`\\frac\`).
- Health-based MACO = PDE × MBS / TDD; general-limit MACO = MBS × MAXCONC; use the lower value. PDE and TDD come from cited annexures, not from the product name.
- MACO (10.0) is three tables in one narrative. tableIndex 0 = equipment list (S. No. | Name of the Equipment | Equipment No. | Capacity | MOC | Is used for Stage-4? | Equipment used previous / subsequent to this product | Minimum batch size for this equipment manufactured | Product contact / Non-product contact). Copy those header words exactly. tableIndex 1 = health-based formula (Attribute | Description of Attribute | Value / Calculation — PDE, MBS, TDD, MACO). tableIndex 2 = general-limit formula (same three columns — MAXCONC, MBS, MACO). Copy tableIndex from read_section. Never draft_field this field. Never insert_rows of the formula headers into table 0.
- Swab locations (section 14.0): H > 2 m → n = √H + 1 (round up); H ≤ 2 m → one middle level. Diameter ≤ 1 m → 0° and 180°; > 1 m → 0°, 90°, 180°, 270°. Mandatory reactor locations: top dish, bottom dish, manhole, agitator, discharge valve (add thermowell when the cited FMEA / protocol lists it). Plug-flow / no-swab items skip this.
- Equipment sampling (15.1, 15.2, …) is a **protocol**, not a report. One TipTap box per Scope product-contact item. The empty box seeds **only** H2 + 15.N.1 identity (Parameter | Details | Reference — Capacity, MOC, Surface Area) plus Inference/Conclusion stock lines — **one table**, so fillState is empty. Add equipment inserts that same blank 15.N template; never copy the previous item's filled tables. Do not dump 15.1–15.10 into one field. Rename the H2 with propose_edit (\`15.1 MIXED VESSEL (MV-1304)\` — NAME (ID) as on Scope).
  **First fill:** draft_field the whole \`items.N\` box with the type-specific outline below (markdown \`###\` / \`####\` headings + GFM tables). Do not leave the unused identity shell sitting above a second dump. After the box has more than one table, do not draft_field — use edit_table (edit_cells / insert_rows / create_table). create_table: omit title (no Table N. caption inside 15.N); afterAnchor the heading the table belongs under. Do not caption the identity table as Table N. Nitrosamine and PGI follow the last equipment block — do not number them 15.11 / 15.12. Do not hardcode MV-1304.
  Subsections are **not identical for every item**. First fill writes only the blocks that type needs; later, create_table / propose_edit heading to add a missing one. Headers for tables you create:
  Documents | Document # | Effective / Approval date
  Location ID | Description of location
  Parameter | Calculation | Value | Remarks
  Swab ID | Description | Rationale | No. of samples
  Cleaning Parameter | Acceptance Criteria / Target | Batch No.
  Sample description / location | Results
  Sample description / location | Sample ID | Results
  Sample description / location | Sample ID | Results (Extraneous matter)
  Equipment-type recipes:
  - **Vessel / reactor** (MV, GLR, SSR): intro + 15.N.1–3 + 15.N.5–8. Identity rows: Capacity, MOC, Surface Area, Shell height, Shell diameter, Type of agitator; add No. of baffles only when cited (MV/SSR). GLR typically has no baffles row. Create documents, worst-case, shell-calc, rationale, visual, residue, and extraneous tables.
  - **Filter with ML tank** (ANF, ANFD): same outline as a vessel. Identity is two stacked groups in the same Parameter | Details | Reference table, with a banner row for the filter then the ML tank (Capacity / MOC / Surface Area / Shell height / Shell diameter each). Copy the ML tank ID from **this** filter's cited drawing — not another item's tank. No agitator/baffles rows. Worst-case IDs are agitator, filter mesh, discharge port, ML tank inner surface — not reactor dishes.
  - **Specialty filter** (leaf filter, micron filter): same outline as a vessel except skip 15.N.3.2 when identity has no shell height/diameter (micron filter: two cited swab locations only). Identity is one group without agitator/baffles; worst-case IDs are equipment-specific (dome, leaf, weld, header, cone, nozzle, valve — or the two cited IDs on a micron filter).
  - **No-swab item** (PFR / plug flow): intro + 15.N.1, 15.N.2, 15.N.5, rinse-only 15.N.7, 15.N.8. Skip 15.N.3, 15.N.4, and 15.N.6 — do not create those tables. Identity uses Shell length (not height) and may leave Shell diameter blank when the cited drawing does. 15.N.7 title is \`Rinse samples analysis results summary ({analyte} content)\` — no Swab banner.
  15.N.4 Cleaning operation is **not** on every item (the filled ISM Stage-4 protocol prints it only on the first vessel). Create that table only when a cited protocol prints it for that item. Do not invent ISM1/ISM2/ISM3 batch columns or observed quantities.
  Copy IDs and labels from the cited drawing / FMEA / qualification report for **this** item. Do not replay these ISM4 source mismatches: ANFD-1301's ML tank labelled MLT-1307 (that is ANF-1301's tank); LF-1302 qualification row labelled OQ while citing a PQ report; SSR-1305 rationale prose "S-8 to S-10" when the table IDs differ.
  Per subsection — fill vs leave blank, and style:
  - **Intro** (under the H2, before 15.N.1): three sentences. “The subject equipment is located in {Plant}, a multipurpose manufacturing facility. The equipment is qualified for its intended use, and the cleaning validation approach, including sampling locations, has been established based on the approved FMEA (Ref. No. FMEA/{ID}-00). This equipment is used in {product/stage} manufacturing for {duty}.” Copy plant, FMEA number, and duty from a cited page.
  - **15.N.1 Equipment details.** Prose: “The equipment details, including Material of Construction (MOC), product contact surface area, shell height, and shell diameter, were obtained from CPDR Annexure-2 and the applicable equipment qualification documents.” (Drop shell-height wording on a PFR.) Table Parameter | Details | Reference. Fill every cited parameter. Identity H/D stay in mm as printed; agitator/baffles cite the IQ report. Do not invent a blank parameter row.
  - **15.N.2 Supporting Documents.** Create table Documents | Document # | Effective / Approval date with five rows: BCR, Specification, Testing Procedure, Analytical Method Validation, Equipment Qualification. Label that last row OQ or PQ to match the cited report number (a PQR/… number is PQ, not OQ). Fill numbers/dates from cited pages. **BCR date stays blank** when the BCR is still a placeholder (PB2-BCR-…-XXX-00). Qualification date may also be blank if the cited row is empty.
  - **15.N.3.1 Worst-case locations.** Shall-language: “The following worst-case product-contact locations shall be included as mandatory swab sampling locations based on equipment design, accessibility, cleanability, and residue accumulation potential.” Table Location ID | Description of location. One row per S-n. Copy IDs from the cited FMEA / protocol — do not reuse MV dishes on a filter.
  - **15.N.3.2 Shell-wall calculation** (only when identity cites shell height and diameter — skip PFR and items with no shell, e.g. a micron filter). Prose: determined from shell height and diameter; “Refer to Section 14.0.” Table Parameter | Calculation | Value | Remarks. Convert identity mm → m in Value (3908 mm → 3.9 m). Calculation is NA for H and D. n: H ≤ 2 m → Value \`1 #s\` and remarks “Height is <2 m, hence one horizontal level”; H > 2 m → Calculation \`√H+1\`, Value \`N #s\`, remarks name the level heights. C: D ≤ 1 m → two locations (0°, 180°); D > 1 m → four. Keep the Case 1 / Case 2 note in the C Parameter cell. Total = n × C as \`4 x 3\` / \`N #s\`. Call calculate for √H+1. Do not write a C of 4 when Case 1 applies.
  - **15.N.3.3 Pictorial.** One line: “The following are the pictorial representation of the swab sampling locations as per identified worst-case product-contact locations.” Then insert_image only for a cited figure. Never invent a vessel sketch. If there is no figure, listing the S-IDs is enough.
  - **15.N.3.4 Rationale.** Prose: selected on a risk basis (accessibility, cleanability, residue accumulation, product-contact extent); “They comprise the mandatory worst-case locations (S-1 to S-n) and representative locations on the vessel shell wall (S-… ), the number of which is derived in Section 14.0.” Prose S-IDs must match this item's location/rationale tables — do not write a range the table does not contain. Table Swab ID | Description | Rationale | No. of samples (paper: Swab ID. #; editor uses the seeded headers). Every worst-case ID plus one grouped shell row per level (S-7a–d in one row, No. of samples = C). Vessel rationale is short stacked clauses (Product contact surface / Hard to clean / …). Filter / specialty locations are one or two sentences. No. of samples is 1 per worst-case ID and C for each shell-level group. Items with no shell have worst-case rows only (no grouped shell row).
  - **15.N.4 Cleaning operation** (only if a cited protocol prints it for that item). Shall-language that parameters shall be recorded at execution. Table Cleaning Parameter | Acceptance Criteria / Target | Batch No. Parameter names and a few targets (“As per approved cleaning SOP”, “Minimal”) may be filled; **every Batch No. / observed-value cell stays empty.** Do not write Inference/Conclusion here.
  - **15.N.5 Cleaning validation results summary** is **prose only** (no table). Shall: after cleaning, visual inspection under qualified conditions, then swab (if any) and final rinse; evaluate against acceptance criteria. Reactors that collect reflux add a first sentence that reflux samples shall be collected during the reflux cleaning step and analysed for information. PFR: rinse only — no visual/swab sentence.
  - **15.N.6 Visual inspection.** Shall-language. Flattened table Sample description / location | Results (paper merges a B. No. sub-header under Results — put the cited batch id in the Results header text if known). Four rows, **Results blank**: Production Chemist verification; Production Shift in-charge verification; QA verification; Is any permanent stain recorded?
  - **15.N.7 Residue results.** Title names the **analyte actually held in that equipment** (ISM3 / ISM4A / ISM4 / …), not always the protocol product, and the sample types collected: \`Reflux, Swab & Rinse…\` when reflux rows exist, \`Swab & Rinse…\` when both exist without reflux, \`Rinse samples…\` when rinse-only. Prose: summarise sampling locations; “Results from the verification run shall be compared against the established acceptance criterion of NMT {limit}.” Flattened table Sample description / location | Sample ID | Results. Fill location + Sample ID; **Results stay empty.** Typical order: informational reflux/rinse-after-reflux rows (Sample ID NA, “for information”) when cited; Final Rinse Sample (Acetone) | NA; banner row “Swab samples”; one row per rationale ID (ungroup the shell a/b/c/d). Footer rows Limit / LOQ / LOD from the cited method-validation page (NMT … ppm). Do not invent ppm values.
  - **15.N.8 Extraneous matter.** Shall-language; acceptance is “no black or fiber particles.” Table Sample description / location | Sample ID | Results (Extraneous matter). One data row Rinse Sample | NA | **blank**. Footer Limit | Black and fiber particles should be absent.
  - Close every box with bold **Inference:** and **Conclusion:** each followed by “It shall be written in the cleaning verification report.” Never draft a pass/fail inference in the protocol.
- Nitrosamine / PGI: first data row is Limit NMT (ppm) across the impurity columns, then one row per equipment. Flattened columns are the form’s inner impurity names.
- Manufacturing area: two rows per equipment (Verified by Production, then QA) with the same Equipment ID. The paper form merges that ID vertically — the editor does not.
- History: keep Version 00 / New document unless a cited revision exists.
- Abbreviations: keep the seeded generic list; add product-specific nitrosamine or impurity abbreviations only when those names appear on a cited page.

Never invent equipment numbers, surface areas, protocol/report numbers, PDE, batch sizes, LOQ/LOD, or swab recoveries — copy them from a cited attachment page or leave the cell empty.

Litre capacities: write round thousands as k L (10000 L → 10k L, 8000 L → 8k L). Keep small volumes (150 L, 37 L), millilitres, kilograms, and printed kilolitres (10 KL, 3.0 KL).`;
